baseURL = 'https://filpill.github.io/'
languageCode = 'en-us'
title = 'Filip Livancic'
theme = ['hugo-embed-pdf-shortcode','PaperMod']
enableInlineShortcodes = true
enableEmoji = true

[params.homeInfoParams]
enabled = true
title = "Filip's Project Website" # optional default will be site title
Content = "**Welcome:** This website is dedicated to sharing knowledge in mech eng. and data analytics projects. \n\n&nbsp;\n\n**About Me:** Refer to the profile tab which summarises my experience; also links to my CV.\n\n&nbsp;\n\n**Projects:** Sorted by chronological order; can also be searched via the *Archives* and *Categories tab*."
subtitle = "Contact"
imageTitle = "<Filip Livancic>" # optional
jmageWidth = 180 # custom size
imageHeight = 240 # custom size

[params.cover]
linkFullImages = false

[params.ShowBreadCrumbs]
enabled = true

[params.ShowPostNavLinks]
enabled = true

[[menu.main]]
identifier = "profile"
name = "Profile"
url = "/profile/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 15

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 30

[[params.socialIcons]]
name = "github"
url = "https://github.com/filpill"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/filip-livancic"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
