baseURL = 'https://filpill.github.io/'
languageCode = 'en-us'
title =  'Filip Livancic'
theme = ['hugo-embed-pdf-shortcode','hugo-PaperMod']
enableInlineShortcodes = true
enableEmoji = true

[markup.goldmark.renderer]
unsafe = true

[params.homeInfoParams]
enabled = true
title = "Filip's Blog" # optional default will be site title
Content = "ğŸ‰ **Welcome:** This website is dedicated to sharing knowledge engineering and data projects. \n\n&nbsp;\n\nğŸ™‹â€â™‚ï¸ **About Me:** Refer to the profile tab which summarises my experience; also links to my CV.\n\n&nbsp;\n\nâœï¸ **Projects:** Sorted by chronological order; can also be searched via the *Archive* and *Tags* tab."
subtitle = "Contact"
imageTitle = "<Filip Livancic>" # optional
jmageWidth = 180 # custom size
imageHeight = 240 # custom size

[params.cover]
linkFullImages = false

[params.ShowBreadCrumbs]
enabled = true

[params.ShowPostNavLinks]
enabled = true

[[menu.main]]
identifier = "home"
name = "ğŸ  Home"
url = "./"
weight = 5

[[menu.main]]
identifier = "profile"
name = "ğŸ‘¤ Profile"
url = "/profile/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "ğŸ“ Archive"
url = "/archives/"
weight = 15

[[menu.main]]
identifier = "tags"
name = "ğŸ·ï¸ Tags"
url = "/tags/"
weight = 30

[[params.socialIcons]]
name = "github"
url = "https://github.com/filpill"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/filip-livancic"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
